### ISSUE TITLE
Release checklist cep18 v1.1

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/cep18#79]
- [ ] (DEV) Close or defer all tickets in the epics (code complete/scope closure) - code freeze
- [ ]  (DEV) Create release candidate branch (branching, tagging)
- [ ]  (Business Owner) Identify destination & distribution targets (communications, announcements)
- [ ]  (SRE) Ensure SRE pipelines are in place
- [ ]  (DEV) unit & Integration tests have passed
- [ ]  (DEV) Create readme in git repo (scope closure)
- [ ]  (DEV) ensure changelog is in place
- [ ]  (SRE) acceptance tests in a production environment has passed
- [ ]  (DEV) Documentation updates are in place (docs team)

**Comment by gRoussac** [comment]
@RBYGLLS can we save this list in confluence and close this "issue" ?

**Comment by RBYGLLS** [comment]
Ok I work on it

**Comment by devendran-m** [comment]
Closing this based on the note from @gRoussac
